# Generated by Django 5.2.5 on 2025-08-25 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_otp'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
